spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
server:
  port: 8080
log:
  file:
    full-path: /home/ajeet/Documents/request-counts.log
feature:
  jobs:
    enabled: true
  http-post:
    enabled: true