server:
  port: 8080
log:
  file:
    full-path: /home/ajeet/Documents/request-counts.log
kafka:
  bootstrapAddress: localhost:9092
  topicName: requests
  enabled: true
  group: api-call-counts
feature:
  jobs:
    enabled: true
  http-post:
    enabled: true
spring:
  mvc:
    throwExceptionIfNoHandlerFound: true